import { AutonomousAgent } from '../types';

export const DEFAULT_AGENTS: AutonomousAgent[] = [
  {
    id: 'agent-alphascalp',
    name: 'AlphaScalp AI',
    tagline: 'Sub-minute Momentum & Micro-Structure Sweeper',
    description: 'High-frequency quantitative engine that detects short-term order book imbalances and rapid RSI bounces at micro-support levels.',
    strategyType: 'MOMENTUM_SCALPING',
    status: 'ACTIVE',
    targetPair: 'BTC/USDT',
    winRateProjected: 74.2,
    profitFactor: 2.34,
    maxDrawdown: 4.1,
    totalTrades: 38,
    winTrades: 29,
    totalPnl: 3420.5,
    executionRules: {
      entryConditions: [
        'RSI (14) dips below 38 on 5m timeframe',
        'EMA 9 crosses EMA 21 to the upside',
        'Volume surge > 1.4x 20-period moving average',
      ],
      exitConditions: [
        'Take Profit 1: +1.2% price gain (auto scale 50%)',
        'Trailing Stop: Locks in +0.6% upon +1.0% expansion',
        'Hard Stop Loss: -0.75%',
      ],
      leverage: 8,
      stopLossPct: 0.75,
      takeProfitPct: 1.8,
      trailingStopPct: 0.5,
      cooldownMinutes: 3,
      positionSizePct: 5,
    },
    systemDirective: 'Aggressive scalp targeting high liquidity depth pools with minimum exposure duration.',
    recentLogs: [
      {
        id: 'log-1',
        time: 'Just now',
        message: 'Scanning BTC/USDT 5m order flow. Order book bid depth 58.2% favorable.',
        type: 'info',
      },
      {
        id: 'log-2',
        time: '4m ago',
        message: 'Executed LONG 0.15 BTC @ $68,120. Reason: EMA 9 bullish crossover confirmed.',
        type: 'trade',
      },
      {
        id: 'log-3',
        time: '18m ago',
        message: 'Closed LONG BTC @ $68,410. Profit: +$43.50 (+0.43% net).',
        type: 'profit',
      },
    ],
  },
  {
    id: 'agent-trendsurfer',
    name: 'TrendSurfer Neural',
    tagline: 'Multi-Timeframe Macro Trend Expansion',
    description: 'Captures sustained directional swings by aligning 15m, 1h, and 4h EMA ribbon expansions with macro trend confirmation.',
    strategyType: 'TREND_FOLLOWING',
    status: 'IDLE',
    targetPair: 'ETH/USDT',
    winRateProjected: 68.8,
    profitFactor: 2.65,
    maxDrawdown: 6.4,
    totalTrades: 22,
    winTrades: 16,
    totalPnl: 5180.2,
    executionRules: {
      entryConditions: [
        'Price closes above 50 EMA on 15m candle',
        'MACD Histogram shifts positive with expanding bars',
        'Funding rate within neutral zone (< 0.02%)',
      ],
      exitConditions: [
        'Candle close below 21 EMA',
        'Target 1: +3.2%, Target 2: +5.8%',
        'Stop loss set at recent swing low (-1.5%)',
      ],
      leverage: 5,
      stopLossPct: 1.5,
      takeProfitPct: 4.2,
      trailingStopPct: 1.0,
      cooldownMinutes: 15,
      positionSizePct: 8,
    },
    systemDirective: 'Ride sustained trend expansions with wide profit targets and trailing risk reduction.',
    recentLogs: [
      {
        id: 'log-t1',
        time: '12m ago',
        message: 'Holding steady. Waiting for 15m candle close above EMA 50 ($3,518).',
        type: 'info',
      },
      {
        id: 'log-t2',
        time: '1h ago',
        message: 'Trailing stop adjusted upward to breakeven on ETH swing position.',
        type: 'alert',
      },
    ],
  },
  {
    id: 'agent-meanrevert',
    name: 'MeanRevert Matrix',
    tagline: 'Statistical Band Reversion & Exhaustion',
    description: 'Exploits overextended market extremes by fading 2-standard-deviation Bollinger Band penetrations accompanied by RSI divergences.',
    strategyType: 'MEAN_REVERSION',
    status: 'ACTIVE',
    targetPair: 'SOL/USDT',
    winRateProjected: 76.5,
    profitFactor: 2.18,
    maxDrawdown: 3.8,
    totalTrades: 45,
    winTrades: 35,
    totalPnl: 4890.0,
    executionRules: {
      entryConditions: [
        'Price pierces outer Bollinger Band (2.0 StdDev)',
        'RSI > 72 (Short entry) or RSI < 28 (Long entry)',
        'Wick rejection candlestick pattern formed',
      ],
      exitConditions: [
        'Price touches 20-period Middle Bollinger Band',
        'Take Profit: +1.6%',
        'Stop Loss: -1.1% beyond extreme wick',
      ],
      leverage: 6,
      stopLossPct: 1.1,
      takeProfitPct: 1.6,
      trailingStopPct: 0.4,
      cooldownMinutes: 10,
      positionSizePct: 6,
    },
    systemDirective: 'Statistical mean reversion back to median value zone after momentum exhaustion.',
    recentLogs: [
      {
        id: 'log-m1',
        time: '2m ago',
        message: 'SOL/USDT RSI at 66.8. Approaching overbought upper band resistance ($186.20).',
        type: 'info',
      },
      {
        id: 'log-m2',
        time: '34m ago',
        message: 'Closed SHORT SOL position at 20-SMA target. Realized PnL: +$112.40.',
        type: 'profit',
      },
    ],
  },
];
